import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../src/components/SessionProvider";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  // useEffect(() => {
  //   if (session) {
  //     // console.log("Hmm");
  //     alert("SESSIIOn");
  //   }
  // });

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
